import { createVSIX } from '@vscode/vsce';
import { mkdir, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pnpm } from './process.mjs';
pnpm(['build']);
await mkdir('artifacts', { recursive: true });
const extension = JSON.parse(await readFile('packages/extension/package.json', 'utf8'));
const helper = JSON.parse(await readFile('packages/helper/package.json', 'utf8'));
await createVSIX({ cwd: 'packages/extension', packagePath: `artifacts/live-webview-${extension.version}.vsix`, dependencies: false, preRelease: process.argv.includes('--pre-release') });
pnpm(['pack', '--out', resolve(`artifacts/webview-dev-helper-${helper.version}.tgz`)], resolve('packages/helper'));
